
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../../src/app/Redux/providers";
import { store } from "../app/Redux/store";
// import { useSessionCheck } from '../app/Redux/hooks/useSessionCheck';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 

  
  return (
    <html lang="en">
      {/* <head>
     
      </head> */}
      {/* <body className={inter.className}>{children}</body> */}
      <body className="font-mulish">
        
        <Providers >
          
        {children}
        </Providers>
          
     
      </body>

    </html>
  );
}
