import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Redux/providers";
// import { UserProvider } from './context/userContext'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={inter.className}>
        {/* Wrap the children with UserProvider */}
        <Providers>
        {children}
        </Providers>
          
       
      </body>

    </html>
  );
}
